### ISSUE TITLE
Fails to compile with a long classpath on Windows

### ISSUE THREAD

**Issue by mkadan** [orfjackal/retrolambda#70]
When retrobmda required a long classpath to compile (in my case it's an Android project with AndroidAnnotations and lot's of dependencies), it generates too long command line to be acceptable for Windows (see http://pastebin.com/vzwP1bdX) and fails to launch java process ("CreateProcess error=206, The filename or extension is too long", see http://pastebin.com/6PpR0npu)

**Comment by orfjackal** [comment]
Yes, long classpaths have problems with the command line limit. Maybe an environment variable could be used instead. That should be simpler than saving the classpath in a file.

**Comment by dynastyX** [comment]
@orfjackal I've encountered with this problem too. cound you please tell me how to fix it?

**Comment by atexit** [comment]
I guess that a manifest-only jar would cover the write classpath in a file solution?

**Comment by orfjackal** [comment]
A manifest-only jar would not work for Retrolambda, because Retrolambda needs to use a custom class loader for #29. I'll implement a command line parameter which reads the classpath from a text file (one entry per line).

**Comment by atexit** [comment]
Thank you for taking the time to explain, @orfjackal !

**Comment by fschoellhammer** [comment]
I am experiencing the same issue. I noticed that once I encounter this problem, I need to clean the project, then it works again (until the issue occurs again some time later). Also, what I saw that the 'long command that fails' lists every class of my project separately. Wouldn't it be possible to just jar the sources before and feed them in as a file instead of separate class files?

**Comment by orfjackal** [comment]
This is included in Retrolambda 2.1.0. The gradle plugin will still need to be updated.
